[package]
name = "balance-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
solana-client = "2.2.0"
solana-sdk = "2.2.1"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
