[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "GekPAWbM5jbvUXzBN7JPV5jAVA6DcJcGuVZCmCY8EogW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
